apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs  
    spec:
      containers: 
      - name: nodongo
        image: richaa741994/my_first_repo:latest
        ports:
        - containerPort: 3000


