apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabel:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: richaa741994/my_first_repo:latest
        ports:
        - containerPort: 3000

